### ISSUE TITLE
Continue loading game even when texture is missing/misspelled

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#27]
Catch error and swap with placeholder image.  

game.js:1 IGE _log_ [$i_114:ige] : Texture image (assets/textures/sprites/generator.png) loaded successfully
game.js:1 Stack:     at e.i [as log](http://villagegamedev2.appspot.com/client/deploy/game.js:1:10604)
 ----     at e.$i_54.extend._applyCells (http://villagegamedev2.appspot.com/client/deploy/game.js:4:11585)
 ----     at e.$i_54.extend._textureLoaded (http://villagegamedev2.appspot.com/client/deploy/game.js:4:10960)
 ----     at HTMLImageElement.ige.isClient.ige._textureImageStore.(anonymous function).e.onload (http://villagegamedev2.appspot.com/client/deploy/game.js:4:1149)
game.js:1 IGE _warning_ [$i_55] : Cell width is a floating-point number! (Image Width 1055 / Number of Columns 3 = 351.6666666666667) in file: assets/textures/sprites/generator.png
game.js:1 IGE _log_ [$i_114:ige] : Texture image (assets/textures/sprites/shop.png) loaded successfully
game.js:1 Stack:     at e.i [as log](http://villagegamedev2.appspot.com/client/deploy/game.js:1:10604)
 ----     at e.$i_54.extend._applyCells (http://villagegamedev2.appspot.com/client/deploy/game.js:4:11585)
 ----     at e.$i_54.extend._textureLoaded (http://villagegamedev2.appspot.com/client/deploy/game.js:4:10960)
 ----     at HTMLImageElement.ige.isClient.ige._textureImageStore.(anonymous function).e.onload (http://villagegamedev2.appspot.com/client/deploy/game.js:4:1149)
game.js:1 IGE _warning_ [$i_55] : Cell width is a floating-point number! (Image Width 1460 / Number of Columns 3 = 486.6666666666667) in file: assets/textures/sprites/shop.png
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/villager.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/flowerPot1.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/fenceSW.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/clothingLine.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/wallSE.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/greendot.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/reddot.png) loaded successfully
game.js:1 IGE _log_ [$i_80] : Audio file (./assets/audio/select.mp3) loaded successfully
game.js:1 IGE _log_ [$i_80] : Audio file (./assets/audio/generalclick04.wav) loaded successfully
game.js:1 IGE _log_ [$i_80] : Audio file (./assets/audio/creatur_footstep_large.mp3) loaded successfully
game.js:1 IGE _log_ [$i_80] : Audio file (./assets/audio/dialogOpen.mp3) loaded successfully
http://villagegamedev2.appspot.com/client/assets/textures/sprites/drill%20truck.png Failed to load resource: the server responded with a status of 404 (Not Found)
![screen shot 2015-03-26 at 2 20 03 pm](https://cloud.githubusercontent.com/assets/1481299/6853725/3e2133ae-d3c3-11e4-8c5c-0ef08586d6e7.png)

**Comment by umutnacak** [comment]
Can we change drill truck.png to drilling truck.png on catalog. My game doesn't continue.

**Comment by darianhickman** [comment]
yep!

On Thu, Mar 26, 2015 at 2:54 PM, umutnacak notifications@github.com wrote:

> Can we change drill truck.png to drilling truck.png on catalog. My game
> doesn't continue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/27#issuecomment-86669157
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman
